### ISSUE TITLE
Cannot open database with target SDK 30 on some Android 11 devices

### ISSUE THREAD

**Issue by brodybits** [storesafe/cordova-sqlite-evcore-extbuild-free#56]
Similar to <https://github.com/storesafe/cordova-sqlite-storage/issues/954>, reproduced on Pixel 5 (via Browser Stack)

This issue does **not** appear with target SDK 30 on Android 11 emulator.

P.S. As I said below, I am planning to implement a different solution compared to cordova-sqlite-storage.

**Comment by PowerMogli** [comment]
Hi Chris, I saw that you released a fix for cordova-sqlite-storage.

We rely on this plugin here because we need to keep the location of the database flexible on Android. However, currently the bug prevents the app from launching.

We would be very grateful if you would commit the fix in this plugin as well.

**Comment by brodybits** [comment]
My apologies for the delay. I am planning to implement a different solution for the evcore and evplus plugin versions.

**Comment by brodybits** [comment]
This should now be resolved in recently published version `0.14.0`.

I will make a similar update for evplus, should be coming early next week.
