### ISSUE TITLE
Volt build Issue when building for Windows - ARM & new target SDK

### ISSUE THREAD

**Issue by hermanluis99** [storesafe/cordova-sqlite-evcore-extbuild-free#62]
I am trying to make a build for Windows with the plugin cordova-sqlite-evcore-extbuild-free but after building it comes with the error below.

I tried chaging the version below 0.12.1 as ARM support has been removed in later releases but is still doesn’t work.

c:\vs2017\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.15063.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting “Retarget solution”. [\plugins\cordova-sqlite-evcore-extbuild-free\src\windows\SQLite3-WinRT-sync\SQLite3\SQLite3.UWP.vcxproj].

I reached out to Volt, but they recommended I go here to see if it's possible to update the NPM, I tried by referencing the github page directly but still no success.

<plugin name="cordova-sqlite-evcore-extbuild-free"  source="git" spec="https://github.com/storesafe/cordova-sqlite-evcore-extbuild-free"/>

**Comment by brodybits** [comment]
related: https://github.com/storesafe/cordova-sqlite-storage/issues/1007

**Comment by brodybits** [comment]
From some more private discussion my understanding is that the Volt build does not support C/C++ compiler on Windows platform, likely not worth further exploring since the Windows platform is now deprecated.

An alternative solution may be to add support for the Electron platform, not sure whether we should discuss here or somewhere else.

**Comment by brodybits** [comment]
Latest update from private discussion is that there is a commercial need to support the Windows platform in the Volt build. Since they do not support building the DLL from C / C++ source, we (I) will need to build the SQLite DLLs separately and specify them in plugin.xml.

I think what we need is documented with some examples here:

- https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#framework

Assuming we continue this effort it will very likely be in a new evplus or evmax plugin version, available under GPL v3 or super/premium commercial license terms.

**Comment by brodybits** [comment]
Closing in favor of https://github.com/storesafe/cordova-sqlite-evmax-build-free/issues/4

Windows ARM support will likely be removed from this plugin version, maybe added to an evmax plugin version if needed for commercial support.
